- name: Install SSH Keys
  authorized_key:
    user: pi
    state: present
    key: "{{ lookup('file', '/home/andrew/.ssh/id_ed25519.pub') }}"

- name: Upgrade packages
  apt:
    update_cache: yes
    upgrade: yes
  become: yes

- name: Prerequisites
  apt:
    pkg:
      gpg
  become: true

- name: Download InfluxDB Repository key
  get_url:
    url: https://repos.influxdata.com/influxdb.key
    dest: /tmp/influxdb.key

- name: Install InfluxDB Repository key
  command: gpg --output /etc/apt/trusted.gpg.d/influxdb.gpg --dearmor /tmp/influxdb.key
  args:
    creates: /etc/apt/trusted.gpg.d/influxdb.gpg
  become: yes

- name: Add InfluxDB repository
  apt_repository:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/influxdb.gpg] https://repos.influxdata.com/debian bullseye stable
  become: yes

- name: Add dialout group
  group:
    name: dialout

- name: Add gpio group
  group:
    name: gpio

- name: Add i2c group
  group:
    name: i2c

- name: Add homeassistant account
  user:
    name: homeassistant
    comment: Home Assistant user
    groups: dialout,gpio,i2c,sudo
    create_home: yes
    password: "{{ password }}"
    system: yes
    append: yes
  become: yes

- name: Install SSH Key for homeassistant account
  authorized_key:
    user: homeassistant
    state: present
    key: "{{ lookup('file', '/home/andrew/.ssh/id_ed25519.pub') }}"
  become_user: homeassistant
  become: yes
