- name: Install InfluxDB
  apt:
    update_cache: yes
    pkg:
      - influxdb2
  become: yes

- name: Start the InfluxDB service
  service:
    name: influxdb
    enabled: yes
    state: started
  become: yes

- name: Check for existing config
  command: influx config list --json
  register: influxdb_config

- name: Configure InfluxDB
  command:
    cmd: >
      influx setup 
        --username andrew
        --password '{{ influxdb_password }}'
        --bucket data 
        --org home
        --retention 0
        --force
  when: influxdb_config.stdout | from_json | length == 0

- name: Create an API Key
  command:
    cmd: influx auth create --all-access --json
  register: influx_auth

- name: Store API Key
  set_fact:
    influxdb_api_key: '{{ (influx_auth.stdout | from_json).token }}'

- name: Install octopus-influx
  pip:
    name:
      - git+https://github.com/planetmarshall/octopus-influx
  become: yes

- name: Install octopus-influx config
  template:
    src: octopus-influx.conf.j2
    dest: /etc/octopus-influx.conf
  become: yes

- name: Test for octopus bucket
  command:
    cmd: >
      influx bucket list 
        --name octopus 
        --org {{ influxdb_organization }}
        --token {{ influxdb_api_key }}
  register: influx_bucket_check

- name: Create bucket for octopus-influx
  command:
    cmd: influx bucket create --name octopus --token {{ influxdb_api_key }}
  when: influx_bucket_check.stdout.startswith('Error')
