- name: Install InfluxDB
  apt:
    update_cache: yes
    pkg:
      - influxdb2
  become: yes

- name: Start the InfluxDB service
  service:
    name: influxdb
    enabled: yes
    state: started
  become: yes

- name: Check for existing config
  command: influx config list --json
  register: influxdb_config

- name: Configure InfluxDB
  command:
    cmd: >
      influx setup 
        --username andrew
        --password '{{ influxdb_password }}'
        --bucket data 
        --org home
        --retention 0
        --force
  when: influxdb_config.stdout | from_json | length == 0

- name: Create write key
  command:
    cmd: influx auth create --write-buckets --read-buckets --json
  register: influx_write_json

- name: Store API Key
  set_fact:
    influxdb_api_write_key: '{{ (influx_write_json.stdout | from_json).token }}'

- name: Create read-only API Key
  command:
    cmd: influx auth create --read-buckets --json
  register: influx_read_json

- name: Store API (Read-only) Key
  set_fact:
    influxdb_api_read_key: '{{ (influx_read_json.stdout | from_json).token }}'

- name: Get organization code
  command:
    cmd: influx org list --json
  register: influx_org_json

- name: Store organization code
  set_fact:
    influxdb_organization_code: '{{ (influx_org_json.stdout | from_json)[0].id }}'

- name: Install octopus-influx
  pip:
    name:
      - git+https://github.com/planetmarshall/octopus-influx
  become: yes

- name: Install octopus-influx config
  template:
    src: octopus-influx.conf.j2
    dest: /etc/octopus-influx.conf
  become: yes

- name: Test for octopus bucket
  command:
    cmd: >
      influx bucket list 
        --name octopus 
        --org {{ influxdb_organization }}
  ignore_errors: true
  register: influx_bucket_check

- name: Create bucket for octopus-influx
  command:
    cmd: influx bucket create --name octopus
  when: influx_bucket_check is failed

- name: Test for home assistant bucket
  command:
    cmd: >
      influx bucket list
        --name "Home Assistant"
        --org {{ influxdb_organization }}
  ignore_errors: true
  register: influx_ha_bucket_check

- name: Create bucket for home assistant
  command:
    cmd: influx bucket create --name "Home Assistant"
  when: influx_ha_bucket_check is failed

- name: Test for telegraf bucket
  command:
    cmd: >
      influx bucket list
        --name telegraf
        --org {{ influxdb_organization }}
  ignore_errors: true
  register: influx_telegraf_bucket_check

- name: Create bucket for telegraf
  command:
    cmd: influx bucket create --name telegraf
  when: influx_telegraf_bucket_check is failed

- name: Retrieve octopus tariff data daily
  cron:
    cron_file: octopus_influx
    name: octopus_influx
    minute: "15"
    hour: "20"
    job: /usr/local/bin/octopus-influx
    user: homeassistant
  become: yes
