---

- name: Reload systemd
  command:
    cmd: systemctl --system daemon-reload
  become: yes

- name: Restart home assistant
  service:
    name: home-assistant@homeassistant
    state: restarted
  become: yes
